version: '3.8'
services:
  app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://admin:admin@mongo:27017/techchallenge?authSource=admin
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    container_name: mongo-db
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: techchallenge
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db

  k6:
    image: loadimpact/k6
    volumes:
      - ./stress-test.js:/scripts/stress-test.js
    command: run /scripts/stress-test.js
    depends_on:
      - app

volumes:
  mongo-data:
