version: '3.8'
services:
  app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_URI: mongodb://mongo:27017/nomeDoBanco
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nomeDoBanco
      MONGO_INITDB_ROOT_USERNAME: usuario
      MONGO_INITDB_ROOT_PASSWORD: senha
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
