name: Deploy Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: techchallenge
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
        volumes:
          - mongo-data:/data/db

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username:
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t your-docker-repo:latest .

      - name: Push Docker image
        run: |
          docker push your-docker-repo:latest

      - name: Deploy to Docker
        run: |
          docker run -d -p 3000:3000 --name node-app \
          -e NODE_ENV=production \
          -e MONGO_URI=mongodb://admin:admin@mongo:27017/techchallenge?authSource=admin \
          your-docker-repo:latest

volumes:
  mongo-data:
